from pydantic import BaseModel, Field
from typing import List, Optional


class RootCauseAnalysis(BaseModel):
    """
    Structured Root Cause Analysis generated by the AI Reasoning Engine (Phase 3).
    """
    cause_chain: List[str] = Field(
        ...,
        description="Chronological event causation chain: e.g. ['Scanner Offline', 'Power Surge', 'UPS Battery Failure', 'Maintenance Overdue']",
    )
    probable_root_cause: str = Field(..., description="The primary root cause: e.g. 'UPS Battery Cell Degradation'")
    confidence_percent: float = Field(..., description="AI confidence rating percentage: e.g. 87.0")
    supporting_evidence: List[str] = Field(
        default_factory=list,
        description="Corroborating telemetry evidence (sensor logs, dwell times, voltage dips)",
    )
    what_happened: str = Field(default="", description="High-level narrative of the failure event")
    expected_consequences: str = Field(default="", description="Cascading downstream risks if unaddressed")


class RecoveryOption(BaseModel):
    """
    Ranked actionable countermeasure generated by AI Decision Matrix (Phase 5).
    """
    option_id: str = Field(..., description="Unique option identifier: e.g. 'OPTION_A'")
    action_type: str = Field(default="ACTIVATE_BACKUP_SCANNER", description="Machine-executable action code")
    action_title: str = Field(..., description="e.g., 'Activate Redundant Scanner Bay B'")
    description: str = Field(..., description="Detailed operational instructions for dispatcher/crew")
    eta_mins: int = Field(..., description="Estimated recovery time in minutes")
    cost_estimate_inr: float = Field(..., description="Financial cost impact in INR")
    risk_level: str = Field(..., description="'Low', 'Medium', or 'High'")
    expected_benefit: str = Field(default="", description="Why this recommendation works and SLA penalty avoided")
    is_recommended: bool = Field(default=False, description="Whether this is the AI primary top-ranked directive")


class ReasoningResult(BaseModel):
    """
    Canonical response returned by POST /incidents/{id}/analyze.
    """
    incident_id: str
    warehouse_id: str = "W12"
    root_cause_analysis: RootCauseAnalysis
    recovery_plan: List[RecoveryOption]
    reasoning_mode: str = "DETERMINISTIC_EXPLAINABLE"