from enum import StrEnum

class EventType(StrEnum):
    # Core Parcel Lifecycle
    PARCEL_CREATED = "PARCEL_CREATED"
    PARCEL_PACKED = "PARCEL_PACKED"
    PARCEL_LOADED = "PARCEL_LOADED"
    PARCEL_DISPATCHED = "PARCEL_DISPATCHED"
    PARCEL_DELIVERED = "PARCEL_DELIVERED"

    # Truck & Telematics
    TRUCK_DEPARTED = "TRUCK_DEPARTED"
    TRUCK_LOCATION_PING = "TRUCK_LOCATION_PING"
    TRUCK_ARRIVED = "TRUCK_ARRIVED"

    # Operational Anomalies & Exceptions
    SCAN_EXCEPTION = "SCAN_EXCEPTION"
    SCANNER_OFFLINE = "SCANNER_OFFLINE"
    TRUCK_DELAY = "TRUCK_DELAY"
    ROUTE_DEVIATION = "ROUTE_DEVIATION"
    WAREHOUSE_OVERLOAD = "WAREHOUSE_OVERLOAD"
    COLD_CHAIN_BREACH = "COLD_CHAIN_BREACH"
    WEATHER_ALERT = "WEATHER_ALERT"

    # Closed-Loop Action & Recovery
    ACTION_EXECUTED = "ACTION_EXECUTED"